### ISSUE TITLE
notebook_drawings.shader - flip video wrong 

### ISSUE THREAD

**Issue by catafest** [przemyslawzaworski/Unity3D-CG-programming#1]
your code flip video , I try to fix but not work is mirrored :
your code 
`float2 uv = ((pos - _ScreenParams.xy*.5) / _ScreenParams.y*_ScreenParams.y) / _ScreenParams.xy + .5;`
my code
`float2 uv = -((pos - _ScreenParams.xy*.5) / _ScreenParams.y*_ScreenParams.y) / _ScreenParams.xy + .5;`

**Comment by przemyslawzaworski** [comment]
In my editor (Unity 5.6.2f1 DX11) old code works perfectly. Screenshot:
https://mega.nz/#!B5YFEKiB!cG63jv94Yx2kXxcXgICWWynAokAVE6NGgVkCYvs1rgo 
And vice versa, your code flips video :)
This is a very interesting issue and strange... Could you describe your system configuration ?
By the way, to enable or disable flipping you can just uncomment or comment line 28.

**Comment by przemyslawzaworski** [comment]
I discovered solution: uv flipping can be caused by enabling/disabling Anti-Aliasing level in Unity Quality Settings (Forward rendering mode).
