### ISSUE TITLE
Font.shader

### ISSUE THREAD

**Issue by smkplus** [przemyslawzaworski/Unity3D-CG-programming#4]
Hi thanks for your amazing shaders. 
I'm trying to Input font shader  by code:
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[ExecuteInEditMode]
public class Font : MonoBehaviour {
    public float[] array;
    public string text;
    public bool Convert;

	void Update () {
        if (Convert)
        {
            array = new float[text.Length];
            for (int i = 0; i < text.Length; i++)
            {
                array[i] = text[i];
            }
            GetComponent<SpriteRenderer>().material.SetInt("_Length", text.Length);
            GetComponent<SpriteRenderer>().material.SetFloatArray("_Array", array);
            Convert = false;
        }
    }
}
```

shader:
````
Shader "Font"
{
	Properties
	{
		_MainTex ("Texture", 2D) = "white" {} //assign font.png (texture source: www.shadertoy.com)
		_Length("Length",Float) = 0
	}
	Subshader
	{
		Tags{ "Queue" = "Transparent" "IgnoreProjector" = "true" "RenderType" = "Transparent" }
		ZWrite Off Blend SrcAlpha OneMinusSrcAlpha Cull Off

		
		Pass
		{
			CGPROGRAM
			
			#pragma vertex vertex_shader
			#pragma fragment pixel_shader
			#pragma target 2.0

			sampler2D _MainTex;
			int _Length;
			float _Array[50];
						
			struct custom_type
			{
				float4 vertex : SV_POSITION;
				float2 uv : TEXCOORD0;
			};
			
			custom_type vertex_shader (float4 vertex : POSITION, float2 uv : TEXCOORD0)
			{
				custom_type vs;
				vs.vertex = UnityObjectToClipPos (vertex);
				vs.uv = uv;
				return vs;
			}

			float4 pixel_shader (custom_type ps) : COLOR
			{
				float2 position = float2(0.5,1.0); //xy coordinates (x: 0.0->1.0 y: 0.0->2.0 )
				float2 U = ps.uv.xy*2.0-position; 
				float c = 0.0;
				float3 d = float3(1.0,1.0,1.0); //RGB font color
				for (int i=0; i<_Length;i++,U.x-=.1)
				{
				int character = _Array[i];
					 c +=(length(U-.06)<.06)?tex2D(_MainTex,U*.5+frac(float2(character,15- character/16)/16.)).x:0.0;
				}
				return float4(c*d.x,c*d.y,c*d.z, float4(c*d.x, c*d.y, c*d.z, 1.0).r);
			}
			ENDCG
		}
	}
}
```

**Comment by przemyslawzaworski** [comment]
I used array with keywords "uniform" or "static", but values from property field aren't visible still.
So I try different approach, for simulating array I use single dimension texture.

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[ExecuteInEditMode]
public class Font : MonoBehaviour 
{

	public Material material;

	void Start ()
	{
		Texture2D image = new Texture2D (4,1, TextureFormat.RGBA32, false);
		Color color1 = new Color (0.65f,0.0f,0.0f, 1.0f); //ASCII 65
		Color color2 = new Color (0.66f,0.0f,0.0f, 1.0f); //ASCII 66
		Color color3 = new Color (0.67f,0.0f,0.0f, 1.0f); //ASCII 67
		Color color4 = new Color (0.69f,0.0f,0.0f, 1.0f); //ASCII 69
		image.SetPixel(0,0,color1);
		image.SetPixel(1,0,color2);
		image.SetPixel(2,0,color3);
		image.SetPixel(3,0,color4);
		image.Apply ();
		material.mainTexture=image;
	}
}`

`Shader "Font"
{
	Properties
	{
		[HideInInspector]
		_MainTex ("Array", 2D) = "white" {}
		MainTex ("Texture font", 2D) = "white" {}
	}
	Subshader
	{
		Pass
		{
			CGPROGRAM
			
			#pragma vertex vertex_shader
			#pragma fragment pixel_shader
			#pragma target 5.0

			sampler1D _MainTex;
			sampler2D MainTex;

			static uint t[4] ;
			
			struct custom_type
			{
				float4 vertex : SV_POSITION;
				float2 uv : TEXCOORD0;
			};
			
			custom_type vertex_shader (float4 vertex : POSITION, float2 uv : TEXCOORD0)
			{
				custom_type vs;
				vs.vertex = UnityObjectToClipPos (vertex);
				vs.uv = uv;
				return vs;
			}

			float4 pixel_shader (custom_type ps) : COLOR
			{
				t[0]=uint(tex1D(_MainTex,0.2).r*100.0);
				t[1]=uint(tex1D(_MainTex,0.4).r*100.0);
				t[2]=uint(tex1D(_MainTex,0.8).r*100.0);
				t[3]=uint(tex1D(_MainTex,1.0).r*100.0);				
				float2 position = float2(0.5,1.0); //xy coordinates (x: 0.0->1.0 y: 0.0->2.0 )
				float2 U = ps.uv.xy*2.0-position; 
				float c = 0.0;
				float3 d = float3(1.0,1.0,1.0); //RGB font color
				for (int i=0; i<4;i++,U.x-=.1)
				{
					 c +=(length(U-.06)<.06)?tex2D(MainTex,U*.5+frac(float2(t[i],15-t[i]/16)/16.)).x:0.0;
				}
				return float4(c*d.x,c*d.y,c*d.z,1.0);
			}
			ENDCG
		}
	}
}`

In CS script is created texture with four pixels, every pixel describes another value. Now shader renders characters, but sometimes values are swapped or incorrect.
