### ISSUE TITLE
VolumeTexture  didn't work

### ISSUE THREAD

**Issue by smkplus** [przemyslawzaworski/Unity3D-CG-programming#5]
Hi Przemysław this didn't work for me
![Capture](https://user-images.githubusercontent.com/16706911/55893040-b767cd00-5bcc-11e9-9017-e502ea15448f.PNG)
![621615261562](https://user-images.githubusercontent.com/16706911/55893043-b8006380-5bcc-11e9-8797-eade34f62aef.PNG)
when I increase dimension I have error
IndexOutOfRangeException: Array index is out of range.

**Comment by przemyslawzaworski** [comment]
Dimension must be the same number as declared in GenerateVolumeTexture (Volume Dimension).

**Comment by smkplus** [comment]
@przemyslawzaworski what number should I use?

**Comment by przemyslawzaworski** [comment]
64 , 128, 256, 512 etc.
